export const ALL_COUNTRIES: readonly { code: string; name: string }[] = [
  { code: "FR", name: "France" },
  { code: "BE", name: "Belgique" },
  { code: "CH", name: "Suisse" },
  { code: "LU", name: "Luxembourg" },
  { code: "MC", name: "Monaco" },
  { code: "DE", name: "Allemagne" },
  { code: "IT", name: "Italie" },
  { code: "ES", name: "Espagne" },
  { code: "NL", name: "Pays-Bas" },
  { code: "AT", name: "Autriche" },
  { code: "PT", name: "Portugal" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "IE", name: "Irlande" },
  { code: "DK", name: "Danemark" },
  { code: "SE", name: "Suède" },
  { code: "FI", name: "Finlande" },
  { code: "PL", name: "Pologne" },
  { code: "CZ", name: "Tchéquie" },
  { code: "RO", name: "Roumanie" },
  { code: "HU", name: "Hongrie" },
  { code: "BG", name: "Bulgarie" },
  { code: "HR", name: "Croatie" },
  { code: "SI", name: "Slovénie" },
  { code: "SK", name: "Slovaquie" },
  { code: "LT", name: "Lituanie" },
  { code: "LV", name: "Lettonie" },
  { code: "EE", name: "Estonie" },
  { code: "GR", name: "Grèce" },
  { code: "CY", name: "Chypre" },
  { code: "MT", name: "Malte" },
  // Add more countries:
  { code: "NO", name: "Norvège" },
  { code: "IS", name: "Islande" },
  { code: "US", name: "États-Unis" },
  { code: "CA", name: "Canada" },
  { code: "JP", name: "Japon" },
  { code: "AU", name: "Australie" },
  { code: "NZ", name: "Nouvelle-Zélande" },
  { code: "BR", name: "Brésil" },
  { code: "MX", name: "Mexique" },
  { code: "IN", name: "Inde" },
  { code: "CN", name: "Chine" },
  { code: "KR", name: "Corée du Sud" },
  { code: "SG", name: "Singapour" },
  { code: "IL", name: "Israël" },
  { code: "AE", name: "Émirats arabes unis" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "MA", name: "Maroc" },
  { code: "TN", name: "Tunisie" },
  { code: "DZ", name: "Algérie" },
  { code: "TR", name: "Turquie" },
  { code: "RU", name: "Russie" },
  { code: "UA", name: "Ukraine" },
  { code: "AD", name: "Andorre" },
  { code: "LI", name: "Liechtenstein" },
  { code: "SM", name: "Saint-Marin" },
  { code: "VA", name: "Vatican" },
] as const;

export type CountryCode = typeof ALL_COUNTRIES[number]["code"];